move heatlh check out of windows path

diff --git a/actions/stripe-mock/action.yml b/actions/stripe-mock/action.yml
--- a/actions/stripe-mock/action.yml
+++ b/actions/stripe-mock/action.yml
@@ -84,10 +84,6 @@ runs:
           nohup ./stripe-mock/stripe-mock.exe -http-addr 127.0.0.1:12111 -https-addr 127.0.0.1:12112 $BETA_ARG $FIXTURES_ARG $SPEC_PATH_ARG > stripe-mock.log 2>&1 &
           sleep 5
           cat stripe-mock.log
-          if ! curl -s -o /dev/null http://127.0.0.1:12111; then
-            echo "stripe-mock failed to start!"
-            exit 1
-          fi
         else
           for i in 1 2 3 4 5; do
             if docker pull stripe/stripe-mock; then
@@ -103,5 +99,16 @@ runs:
 
           docker run -d -p 12111-12112:12111-12112 \
             -v "${{ github.workspace }}:/workspace" \
-            stripe/stripe-mock $BETA_ARG $FIXTURES_ARG $SPEC_PATH_ARG && sleep 7
+            stripe/stripe-mock $BETA_ARG $FIXTURES_ARG $SPEC_PATH_ARG
+          sleep 7
+        fi
+
+        if ! curl -s -o /dev/null http://127.0.0.1:12111; then
+          echo "stripe-mock failed to start!"
+          if [ "${{ runner.os }}" != "Windows" ]; then
+            docker logs $(docker ps -lq)
+          else
+            cat stripe-mock.log
+          fi
+          exit 1
         fi
