validate

diff --git a/actions/stripe-mock/action.yml b/actions/stripe-mock/action.yml
--- a/actions/stripe-mock/action.yml
+++ b/actions/stripe-mock/action.yml
@@ -26,7 +26,6 @@ runs:
       shell: bash
       run: |
         BETA_ARG=""
-        OPENAPI_VERSION=""
         FIXTURES_ARG=""
         SPEC_PATH_ARG=""
         CURL_OPTS=(--retry 3 \
@@ -52,6 +51,11 @@ runs:
         if [ -n "${{ inputs.openapi_version }}" ]; then
           if [ -n "${{ inputs.spec_path }}" ]; then
             echo "Error: Pass either an OpenAPI version or a spec path, not both"
+            exit 1
+          fi
+
+          if ! [[ "${{ inputs.openapi_version }}" =~ ^v[0-9]+$ ]]; then
+            echo "Error: Invalid OpenAPI version format. It should be in the format 'v<number>', e.g., 'v1', 'v2', etc."
             exit 1
           fi
 
