check

diff --git a/actions/enable-auto-merge/action.yml b/actions/enable-auto-merge/action.yml
--- a/actions/enable-auto-merge/action.yml
+++ b/actions/enable-auto-merge/action.yml
@@ -27,6 +27,11 @@ runs:
       run: |
         set -e -o pipefail
 
+        if [ "${{ inputs.pr_url }}" == "" ]; then
+          echo "PR URL is required"
+          exit 1
+        fi
+
         PR_ID=$(gh pr view ${{ inputs.pr_url }} --json id --jq ".id")
 
         gh api graphql -f query='
